Yup-io/app-frontend

src/components/Collections/CollectionEditDialog.js
src/components/Collections/CollectionPostDialog.js
src/components/Header/Header.js
src/components/ProfileCard/ProfileCard.js
src/components/YupLeaderboard/ListHOC.js
src/components/YupLeaderboard/ListPostGrid.js
src/components/YupLeaderboard/ListPreview.js
src/pages/Collections/Collections.js
src/pages/Search/Search.js
src/pages/User/User.js
src/styles.css

This reverts commit 649bc8af744ee537ccae00266ff325443945dd82, reversing
changes made to da5599596fbd8d9f8135db76eb891f453c5755cb.

Revert "Merge pull request #9 from Yup-io/dw-collection"

---

src/components/VoteComp/VoteComp.js

Votecomp was overflowing into the audius leaderboard, see: https://www.notion.so/yup/audius-leaderboard-embed-styling-dc2cbd383a894651946b7c826122878e

max width for votecomp

---

src/components/CustomTweetEmbed/CustomTweetEmbed.js
src/components/EditProfile/EditProfile.js
src/components/Post/PostHOC.js
src/components/ProfileCard/ProfileCard.js
src/components/TopBar/TopBar.js
src/components/VoteButton/VoteButton.js
src/components/VoteComp/VoteComp.js
src/pages/Collections/Collections.js
src/pages/Discover/Discover.js
src/pages/PostPage/PostPage.js
src/pages/User/User.js

[https://www.notion.so/yup/App-bug-fixes-f0da28c2a6294a3a86b698fc3d09073e](url)

more bug hunt fixes

---

src/components/SubscribeDialog/SubscribeDialog.js

https://www.notion.so/yup/Change-ETH-Sign-up-copy-7a0a52db3a99499b9841fa07858c8479

Changed copy

---

src/components/Collections/CollectionPostDialog.js
src/components/Collections/RecommendedCollections.js
src/pages/Collections/Collections.js
src/pages/Index.js
src/pages/User/User.js

- Fixed spacing for recommended collections
- "Show all" was hidden on mobile + floating to the right -> centered now 
-  Encoded collectionnames when routing, so ? and / doesnt break the router

Di bughunt fixes

---

src/components/Collections/CollectionEditDialog.js
src/components/Collections/CollectionPostDialog.js
src/components/EditProfile/EditProfile.js
src/components/Miscellaneous/LoaderButton.js
src/components/Miscellaneous/YupInput.js

- reusable component for input fields and integration
- reusable component for loader buttons and integration
- default values for name and descriptions in edit dialog
- minor styling changes

Fix merge web refactor

---

src/components/TopBar/TopBar.js
src/components/VoteButton/VoteButton.js
src/eos/actions/push-transaction.js
src/eos/actions/vote.js
src/pages/Index.js
src/pages/TwitterOAuth/TwitterOAuth.js

twitter-voting from the frontend
(make sure to merge ts-twitter-voting PR on backend as well)

ts-twitter-voting

---

src/components/Header/Header.js
src/components/TopBar/TopBar.js

Fix: notifications prof drilling from header -> topbar -> notif comp
Fix: profile image flicker / rerenders in topbar

rf/fix: notifs rerender + profile img flicker in topbar

---

src/components/Collections/CollectionPostDialog.js
src/components/EditProfile/EditProfile.js
src/components/Followers/FollowingDialog.js
src/components/LinkPreview/ArticlePreview.js
src/components/LinkPreview/NFTPreview.js
src/components/LinkPreview/ObjectPreview.js
src/components/Miscellaneous/YupInput.js
src/components/Notification/NotifPopup.js
src/components/Post/ArticlePost.js
src/components/Post/PostController.js
src/components/PostHeader/PostHeader.js
src/components/ProfileCard/ProfileCard.js
src/components/SearchBar/SearchBar.js
src/components/SubscribeDialog/SubscribeDialog.js
src/components/TopBar/TopBar.js
src/components/YupLeaderboard/CategoryMenu.js
src/components/YupLeaderboard/ListPreview.js
src/components/YupLeaderboard/SiteMenu.js
src/components/YupLeaderboard/SubjectMenu.js
src/components/YupLeaderboard/YupListSearchBar.js
src/components/YupLeaderboard/YupListsMenu.js
src/pages/Analytics/Analytics.js
src/pages/Discover/Discover.js
src/pages/User/User.js
src/pages/YupLists/YupLists.js
src/utils/colors.js
src/utils/theme.js
yarn.lock

@verminator23 this should be merged asap

Update styling to match style guidelines and theme.js

---

.env
.env.dev
package-lock.json
package.json
src/components/Landing/HomeMenu.js
src/components/LinkPreview/NFTPreview.js
src/components/Miscellaneous/CldImg.js
src/components/Miscellaneous/CldVid.js
src/components/Post/NFTPost.js
src/pages/PostPage/PostPage.js
src/utils/cloudinary.js
yarn.lock

currently integrated for NFT previews (tend to be large file sizes) and for homemenu

Cloudinary img and vid components to optimize formating/sizing

---

package.json
src/pages/Index.js
yarn.lock

Readding the gtag manager without breaking the navigation

add gtag package

---

src/components/CustomTweetEmbed/Original.js
src/components/Feed/FeedHOC.js
src/components/Post/TextPost.js
src/components/TopBar/TopBar.js

bug fixes causing errors in webapp

ts-post-cleanup

---

src/components/Post/PostController.js
src/components/TopBar/TopBar.js

fix regEx and unhide mirror articles item from sidebar

Mirror feed fixes

---

src/components/Charts/BarChart.js
src/components/Charts/DonutChart.js
src/components/Charts/LineChart.js
src/components/Charts/RadialChart.js
src/components/Feed/FeedHOC.js
src/components/FeedLoader/ListLoader.js
src/components/Followers/FollowButton.js
src/components/Landing/HomeMenu.js
src/components/Post/PostHOC.js
src/components/ProfileCard/ProfileCard.js
src/components/TopBar/TopBar.js
src/components/UserAvatar/UserAvatar.js
src/components/YupLeaderboard/ListHOC.js
src/components/YupLeaderboard/ListPreview.js
src/components/YupLeaderboard/YupList.js
src/components/YupLeaderboard/YupListFeed.js
src/components/YupLeaderboard/YupListsMenu.js
src/pages/Analytics/Analytics.js
src/pages/Collections/Collections.js
src/pages/Index.js
src/pages/User/User.js
src/pages/YupLists/YupLists.js
src/utils/colors.js
src/utils/theme.js

@ericHgorski please merge these and continue to clean up! I completed most of the tasks currently set

Nk minidrawer

---

src/components/Post/AudiusPost.js
src/components/ProfileCard/ProfileCard.js
src/components/Tour/Tour.js
src/components/VoteButton/VoteButton.js
src/pages/User/User.js

https://app.clickup.com/t/1p035da

Changeing wording to "Yup Score"

---

src/pages/User/User.js

avoid destructuring null error

fix for users without a bio

---

src/components/Landing/HomeMenu.js
src/components/Notification/Notification.js
src/components/TopBar/TopBar.js

- move extension link below
- update notif image object-fit
- padding on home

quick revisions

---

src/components/Followers/FollowersDialog.js
src/components/Followers/FollowingDialog.js
src/components/TopBar/TopBar.js
src/pages/User/User.js
src/utils/theme.js

- padding clean up
- collections buttons fix to chip and add button is smaller

- clean up profile page

---

src/components/Charts/LineChart.js
src/components/Collections/RecommendedCollections.js
src/components/Comments/Comment.js
src/components/CustomTweetEmbed/CustomTweetEmbed.js
src/components/CustomTweetEmbed/HeaderSection.js
src/components/CustomTweetEmbed/Quoted.js
src/components/CustomTweetEmbed/Reply.js
src/components/Landing/HomeMenu.js
src/components/LinkPreview/ArticlePreview.js
src/components/LinkPreview/NFTPreview.js
src/components/LinkPreview/ObjectPreview.js
src/components/Notification/Notification.js
src/components/Post/PostHOC.js
src/components/Post/TextPost.js
src/components/Post/TweetPost.js
src/components/ProfileCard/ProfileCard.js
src/pages/Collections/Collections.js
src/pages/User/User.js
src/utils/theme.js

Nk grid cleanup ext

---

src/components/CustomTweetEmbed/Avatar.js
src/components/CustomTweetEmbed/CustomTweetEmbed.js
src/components/CustomTweetEmbed/HeaderSection.js
src/components/CustomTweetEmbed/Original.js
src/components/CustomTweetEmbed/Quoted.js
src/components/CustomTweetEmbed/Reply.js
src/components/CustomTweetEmbed/Retweet.js
src/components/CustomTweetEmbed/TweetVidPlayer.js
src/components/Post/TweetPost.js
src/pages/Collections/Collections.js
src/utils/theme.js

nk-tweet revisions into master

CU-1zp03na_Tweet-Embed-Revision-121_Nir

---

src/components/Collections/CollectionDialog.js
src/components/Collections/CollectionDuplicateDialog.js
src/components/ConnectEth/ConnectEth.js
src/components/Followers/FollowersDialog.js
src/components/Followers/FollowingDialog.js
src/components/SubscribeDialog/SubscribeDialog.js
src/utils/theme.js

Nk dialog cleanup

---

src/pages/StakingPage/Staking.js

Handle edge cases:
- don't show an error if the API request is successful but the user has absolute 0 balance
- don't show the collect button if the user has nothing to collect

fix: handle edge cases - Staking Page

---

src/pages/StakingPage/Staking.js

Ticket: [CU-232jtr4](https://app.clickup.com/t/232jtr4)
Description: Fix issue with text counting up on Staking page flickering as the value changes.

CU-232jtr4: Fix issue with CountUp text flickering

---

.env
.env.dev
src/apis/accounts.js
src/apis/base_api.js
src/apis/eth.js
src/apis/index.js
src/components/ConnectEth/ConnectEth.js
src/config/index.js
src/constants/enum.js
src/pages/Index.js
src/redux/actions/account.actions.js

Ticket: https://app.clickup.com/t/22wpkkr
Description: Fix issue with user's eth address being updated on Staking page even though the address already exists

CU-22wpkkr: Fix issue with user's eth address being updated when the address already exists

---

src/components/ConnectEth/ConnectEth.js
src/pages/StakingPage/Staking.js

- **ClickUp Task:** https://app.clickup.com/t/22wpuh1
- **Other References:** None
Allow users connect ETH wallet to stake even if they are not logged in

CU-22wpuh1: Allow users connect ETH when they are not logged in

---

src/components/SubscribeDialog/SubscribeDialog.js
src/redux/actions/account.actions.js

- **ClickUp Task:** https://app.clickup.com/t/23t7hh1
- **Other References:** None
Quick solution for login/signup with Metamask.
There will be follow-up PRs for moving logic into a React context, converting class component into a functional component.

CU-23t7hh1: Add Login with Metamask

---

package.json
src/apis/accounts.js
src/apis/auth.js
src/apis/eth.js
src/apis/index.js
src/components/AuthInput/AuthInput.js
src/components/AuthInput/AuthInputStyles.js
src/components/AuthMethodButton/AuthMethodButton.js
src/components/AuthMethodButton/AuthMethodButtonStyles.js
src/components/AuthMethodButton/index.js
src/components/SideBar/SideBar.js
src/components/TopBar/TopBar.js
src/config/index.js
src/constants/enum.js
src/constants/messages.js
src/contexts/WalletContext.js
src/features/AuthModal/AuthModal.js
src/features/AuthModal/AuthModalStyles.js
src/features/AuthModal/index.js
src/index.js
src/utils/analytics.js
src/utils/eth.js
src/utils/helpers.js
yarn.lock

- **ClickUp Task:** https://app.clickup.com/t/2td63u3
- **Other References:** None
- Create a modal component for sign-in/sign-up
- Define a react context for handling wallets

CU-2td63u3: Refactor auth modal

---

src/components/Charts/BarChart.js
src/components/Charts/DonutChart.js
src/components/Charts/LineChart.js
src/components/Charts/RadialChart.js
src/pages/StakingPage/Staking.js
src/utils/theme.js

cleaned up colors and backgrounds

---

src/components/PostGrid/PostGrid.js

Wrap VoteComp with Suspense

---

src/components/Post/NFTPost.js
src/components/Post/PostController.js

Add refetch preview back

---

src/components/Notification/NotifPopup.js
src/components/PostHeader/PostHeader.js
src/components/TopBarAndDrawer/TopBarAndDrawer.js

- [x ] I reviewed changes by myself.
- [x ] I tested the changes in Desktop Mode.
- [x ] I tested the changes in Mobile Mode.

add opacity

---

src/components/Landing/styles.js

- **ClickUp Task:** https://app.clickup.com/t/33t2dj4

Fix issue with logo overflowing on landing page

---

src/_pages/ScorePage/ScorePage.js
src/_pages/Search/Search.js
src/_pages/TwitterOAuth/TwitterOAuth.js
src/_pages/User/User.js
src/components/Collections/RecommendedCollections.js
src/components/EditProfile/EditProfile.js
src/components/FeedContainer/FeedHeader.js
src/components/Landing/HomeMenu.js
src/components/Notification/NotifPopup.js
src/components/PostHeader/PostHeader.js
src/components/ProfileCard/ProfileCard.js
src/components/ScorePage/EnsCard.js
src/components/ScorePage/ScoreCard.js
src/components/TopBarAndDrawer/TopBarAndDrawer.js
src/components/VoteButton/VoteButton.js
src/components/VoteComp/VoteComp.js
src/eos/scatter/scatter.wallet.js
src/themes/_helpers.js

- **ClickUp Task:** https://app.clickup.com/t/2nbmw42

Nf app bug fixes

---

package.json
src/index.js
src/redux/store.js
yarn.lock

- **ClickUp Task:** https://app.clickup.com/t/36uap4n

Nf remove redux logger

---

package.json
src/components/PostHeader/PostHeader.js
src/components/ProfileCard/ProfileCard.js

fix: double Post headers & profile likes count

---

src/components/TopBarAndDrawer/StyledFirstMenuList.js
src/constants/data.js
src/redux/actions/feed.actions.js
src/redux/reducers/feed.reducer.js
src/utils/analytics.js

- [ x] I reviewed changes by myself.
- [x ] I tested the changes in Desktop Mode.
- [ x] I tested the changes in Mobile Mode.

change routes

---

src/_pages/Analytics/Analytics.js
src/components/Charts/BarChart.js
src/components/ProfileCard/ProfileCard.js
src/components/TopBarAndDrawer/TopBarAndDrawer.js

Fix issue with Yup Score

---

package.json
src/_pages/StakingPage/Staking.js
src/features/RKProvider/RKProvider.js
yarn.lock

- [ x] I reviewed changes by myself.
- [ x] I tested the changes in Desktop Mode.
- [ x] I tested the changes in Mobile Mode.

Di fix contracts

---

src/components/Landing/HomeMenu.js

- **ClickUp Task:** https://app.clickup.com/t/2rjhhf2

Fix: Reduce spacing when there's no collection

---

src/components/SideBar/UserMenuItem.js
src/contexts/AuthContext.js
src/contexts/AuthModalContext/AuthModalContext.js

- **ClickUp Task:** https://app.clickup.com/t/3acvd1b

Remove xxx from profile link

---

src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/HeaderSection.js
src/components/CustomWeb3PostEmbed/LensPost.js
src/components/ReactMarkdown.js
src/themes/_helpers.js

Di truncate

---

src/components/UserCollectionsSection/UserCollectionsSection.js
src/components/UserNewConnections/UserNewConnections.js
src/components/UserNewConnections/index.js
src/components/UserRecommendedConnection/UserRecommendedConnection.js
src/components/UserRecommendedConnection/index.js
src/hooks/queries.js
src/pages/account/[username].js

- **ClickUp Task:** https://app.clickup.com/t/3acme0r

Show related people on profile page when there's no collection

---

src/redux/actions/feed.actions.js

Update feed endpoint for daily hits

---

src/components/Followers/FollowButton.js
src/components/ProfileCard/ProfileCard.js
src/components/ProfileHeader/ProfileHeader.js

Di follow/unfollow

---

src/components/VoteComp/VoteComp.js

- [x ] I reviewed changes by myself.
- [x ] I tested the changes in Desktop Mode.

use like variable in votes

---

src/components/Feed/FeedHOC.js
src/components/SideBar/SideBar.js
src/contexts/AuthContext.js

- **ClickUp Task:** https://app.clickup.com/t/3ar6mt4

Fix logout logic, close Settings modal on logout

---

src/components/ConnectButton/ConnectButton.js
src/constants/messages.js
src/contexts/AuthModalContext/AuthModalContext.js

fix signup issues

---

src/components/VoteButton/VoteButton.js
src/components/VoteComp/VoteComp.js
src/eos/error.js

- [x ] I reviewed changes by myself.

fix vote numbers ||error handling

---

src/components/SearchUi/SearchPosts.js
src/components/SearchUi/SearchUi.js
src/hooks/queries.js

- **ClickUp Task:** https://app.clickup.com/t/2t3r7fp

Fix issue with pagination on Search

---

src/components/LinkPreview/ArticlePreview.js

- **ClickUp Task:** https://app.clickup.com/t/3ar7urg

Fix issue with link color in Feed

---

src/components/CustomWeb3PostEmbed/Original.js
src/components/Landing/HomeMenu.js

Di recommended float

---

package.json
src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/LensPost.js
src/components/CustomWeb3PostEmbed/Util/Util.js
src/components/LinkPreview/ArticlePreview.js
src/components/Miscellaneous/SeeMore.js
src/components/Post/ArticlePost.js
src/components/Post/PostController.js
yarn.lock

- [x ] I reviewed changes by myself.
- [x ] I tested the changes in Desktop Mode.

Di linkpreview

---

src/contexts/AuthContext.js

- **ClickUp Task:** https://app.clickup.com/t/2u4djgh

Remove xxx from profile link when user logs in from extension

---

src/hooks/queries.js
src/pages/account/[username].js

- **ClickUp Task:** https://app.clickup.com/t/3b3p2qt

Show proper error text when profile does not exist

---

src/components/CustomWeb3PostEmbed/HeaderSection.js

- **ClickUp Task:** https://app.clickup.com/t/3b3p4t8

Remove link for farcaster, lens posts

---

src/components/CustomWeb3PostEmbed/HeaderSection.js

- **ClickUp Task:** https://app.clickup.com/t/2t3rb3p

Link lens users to lenster profile

---

src/components/UserAnalytics/UserAnalytics.js

- **ClickUp Task:** https://app.clickup.com/t/3b979rq

Swap Yup Score and Influence on Analytics Page

---

src/components/CustomWeb3PostEmbed/LensPost.js
src/components/Miscellaneous/CldImg.js

- **ClickUp Task:** https://app.clickup.com/t/2u4djgh

Fix issue with IPFS image links

---

src/components/Collections/CollectionPostMenu.js

- **ClickUp Task:** https://app.clickup.com/t/3b3k9t1

Add limit to height of collection dropdown

---

src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/HeaderSection.js
src/components/CustomWeb3PostEmbed/Reply.js
src/components/CustomWeb3PostEmbed/ThumbnailIcon.js

- **ClickUp Task:** https://app.clickup.com/t/2tmyk05

Add farcaster post link on thumbnail icon

---

src/components/LinkPreview/ArticlePreview.js
src/components/VoteComp/VoteComp.js

- **ClickUp Task:** https://app.clickup.com/t/2u4djgh

Nf ds followup

---

src/components/CollectionDetails/CollectionDetails.js
src/components/Feed/FeedHOC.js
src/components/YupHead.js
src/contexts/AuthContext.js
src/pages/account/[username].js
src/pages/analytics/[username].js
src/pages/feed/[category].js
src/pages/leaderboard.js

- **ClickUp Task:** https://app.clickup.com/t/3ajgu1c

Use appropriate meta tags for pages

---

src/components/Collections/RecommendedCollections.js
src/components/LinkPreview/ArticlePreview.js

- **ClickUp Task:** https://app.clickup.com/t/2u4djgh

remove react-down and add remove-markdown to ArticlePreview.js

---

src/components/CollectionDetails/CollectionList.js
src/components/Post/PostDisplay.js
src/components/RecommendedPosts/RecommendedPosts.js
src/components/RecommendedPosts/index.js
src/hooks/queries.js
src/pages/post/[id].js

- **ClickUp Task:** https://app.clickup.com/t/3bmv1tq

Show recommendation posts on Post and Collections pages

---

src/components/Post/PostDisplay.js
src/components/RecommendedPosts/RecommendedPosts.js

Implement excluded ids

---

src/hooks/queries.js

- **ClickUp Task:** https://app.clickup.com/t/3bufad0

Pre-process search query for recommendation posts

---

src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/Reply.js
src/components/YupReactMarkdown.js

- **ClickUp Task:** https://app.clickup.com/t/3bueu7n

Fix issue with padding for linkPreview on web3 posts

---

src/components/CustomTweetEmbed/CustomTweetEmbed.js
src/components/CustomTweetEmbed/Original.js
src/components/CustomTweetEmbed/Quoted.js
src/components/CustomTweetEmbed/Reply.js
src/components/CustomTweetEmbed/Retweet.js
src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/Original.js
src/components/Miscellaneous/CldImg.js
src/components/YupImage/YupTweetImg.js
styles/global.css

Di mobile fixes

---

src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/Original.js
src/components/CustomWeb3PostEmbed/Util/Util.js

Di web3links

---

src/components/CustomWeb3PostEmbed/Reply.js

- **ClickUp Task:** https://app.clickup.com/t/3bum3bh

Link parent post to child post page

---

src/components/SideBar/SideBar.js
src/constants/data.js
src/redux/actions/feed.actions.js
src/redux/reducers/feed.reducer.js
src/utils/analytics.js

remove politics and safespace

---

src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/Reply.js
src/components/CustomWeb3PostEmbed/Util/Util.js
src/components/LinkPreview/LinkPreview.js
src/components/Miscellaneous/CldImg.js

Di farcaster fixes

---

src/components/ProfileHeader/ProfileHeader.js
src/hooks/queries.js

- **ClickUp Task:** https://app.clickup.com/t/3c098kc

Add ENS name for ETH addresses

---

src/components/BackToTop/BackToTop.js
src/components/BackToTop/index.js
src/components/MainLayout/MainLayout.js
src/components/ProfileHeader/ProfileHeader.js

- **ClickUp Task:** https://app.clickup.com/t/3c09c0q

Feature: Add a button to connect wallet on profile page, add Go To Top button

---

src/components/LinkPreview/ArticlePreview.js
src/components/LinkPreview/FullArticle.js
src/components/Post/ArticlePost.js
src/components/Post/PostController.js
src/components/YupReactMarkdown.js

Di mirror full

---

src/components/MainLayout/MainLayout.js
src/components/ProfileHeader/ProfileHeader.js

- **ClickUp Task:** https://app.clickup.com/t/3c09bvj

Show Snackbar message on profile, disable GoToTop

---

src/components/Collections/CollectionDialog.js
src/components/VoteComp/VoteComp.js
src/contexts/AuthContext.js

Di eos refetch

---

src/components/ProfileHeader/ProfileHeader.js
src/hooks/useToast.js
src/providers/SnackbarProvider.js

- **ClickUp Task:** https://app.clickup.com/t/3c09c0q

Make Snackbar clickable

---

src/components/CustomWeb3PostEmbed/CustomWeb3PostEmbed.js
src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/LensPost.js
src/components/CustomWeb3PostEmbed/Original.js
src/components/LinkPreview/FullArticle.js
src/components/Post/ArticlePost.js
src/components/Post/PostController.js
src/components/Post/PostDisplay.js
src/components/Post/Web3Post.js
src/components/YupReactMarkdown.js

- **ClickUp Task:** https://app.clickup.com/t/2rcrup9

Fix issue with styling on post page

---

src/components/CustomWeb3PostEmbed/LensPost.js
src/components/YupReactMarkdown.js

phaver images

---

src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/Reply.js
src/components/Post/PostController.js
src/components/VideoComponent/VideoComponent.js
src/components/VideoComponent/index.js
src/utils/helpers.js
src/utils/post_helpers.js

- **ClickUp Task:** https://app.clickup.com/t/3acnazt

Embed YouTube video directly on Web3 Posts

---

src/components/RecommendedPosts/RecommendedPosts.js
src/components/UserPosts/UserPosts.js
src/pages/account/[username].js

- **ClickUp Task:** https://app.clickup.com/t/3c0avau

Added recommended posts on Profile Page

---

src/components/CustomWeb3PostEmbed/LensPost.js
src/components/Feed/FeedHOC.js
src/components/YupReactMarkdown.js
src/utils/helpers.js

Embed youtube link directly on Lens Posts

---

src/components/Post/PostController.js
src/components/UserRecommendedConnection/UserRecommendedConnection.js
src/services/feeds.js

feed default case

---

src/hooks/queries.js

Fix issue with feed endpoint issue

---

src/hooks/queries.js

Update feed endpoint for recent feeds on Staging

---

src/components/SideBar/UserMenuItem.js

close search

---

src/components/Post/PostController.js
src/pages/_app.js
src/pages/post/[id].js

- **ClickUp Task:** https://app.clickup.com/t/3cbpf2z

Convert Post page into SSR

---

src/pages/account/[username].js

- **ClickUp Task:** https://app.clickup.com/t/3ddxb46

Convert Profile Page into SSR

---

src/components/Followers/FollowingDialog.js

- **ClickUp Task:** https://app.clickup.com/t/3de5mg0

Fix issue with profile followers

---

src/components/Collections/RecommendedCollections.js

username in collection

---

src/components/CustomTweetEmbed/CustomTweetEmbed.js
src/components/Followers/FollowersDialog.js

Update followers api

---

src/apis/base_api.js
src/components/ProfileHeader/ProfileHeader.js
src/hooks/queries.js

- **ClickUp Task:** https://app.clickup.com/t/3guutta

Return null instead of exception in api calls

---

src/_pages/StakingPage/Staking.js
src/constants/enum.js
src/hooks/queries.js

total rewards

---

src/components/YupHead.js
src/constants/const.js
src/pages/post/[id].js
src/utils/helpers.js

- **ClickUp Task:** https://app.clickup.com/t/3h0j9a5

Add meta tags to post page

---

src/pages/post/[id].js

revert postpage contentRight

---

src/components/Post/PostHOC.js
src/components/PostCard/PostCard.js

Di app fixes

---

src/components/CollectionDetails/CollectionDetails.js
src/pages/account/[username].js

- **ClickUp Task:** https://app.clickup.com/t/3cbq76m

Update meta tags for Profile and Post pages

---

src/components/Heads/PostHead.js
src/components/Heads/index.js
src/constants/enum.js
src/pages/post/[id].js

CU-3h0j9a5: Update meta tags for mirror and poaps

---

src/components/YupHead.js

Update meta description

---

src/components/EditProfile/EditProfile.js

CU-3jkzw30: Fix issue with updating profile data

---

src/components/VoteButton/VoteButton.js
src/components/VoteComp/VoteComp.js

CU-30cx53q: Fix UI issue with vote count

---

src/apis/base_api.js
src/contexts/AuthModalContext/AuthModalContext.js

CU-3jtn8t2: Fix issue with Sign Up w/ wallet

---

src/components/UserWallet/Tokens.js

CU-3hbuu3h: Align two sections on Wallet page

---

src/components/CollectionDetails/CollectionPostList.js
src/components/CustomTweetEmbed/CustomTweetEmbed.js
src/components/CustomTweetEmbed/TweetVidPlayer.js
src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/UserPosts/UserPosts.js
src/pages/account/[username].js
src/utils/post_helpers.js

Di app fixes 23 09

---

src/components/UserWallet/UserWallet.js
src/components/YupPageHeader/YupPageHeader.js
src/components/YupPageHeader/styles.js
src/contexts/AppUtilsContext.js

CU-3jkzuum: Fix/scroll behavior

---

src/components/CustomTweetEmbed/Reply.js
src/components/CustomTweetEmbed/TweetVidPlayer.js

CU-3k532kt: Fix issue with tweet video on post page

---

src/components/Feed/FeedHOC.js
src/hooks/queries.js

Di personalized feed

---

src/_pages/StakingPage/Staking.js
src/components/FollowButton/FollowButton.js
src/components/UserRecommendedConnection/UserRecommendedConnection.js
src/components/styles.js

Di app fixes 26 09

---

src/hooks/queries.js

Di fix feedquery

---

src/components/Landing/HomeMenu.js

CU-3k534gz: Fix issue with zIndex for card

---

src/contexts/AuthModalContext/AuthModalContext.js

CU-3jtn96b: Show rainbow kit when click Connect

---

src/contexts/AuthModalContext/AuthModalContext.js

CU-32hm613: Update text for wallet login

---

src/components/VoteButton/VoteButton.js

CU-3katnpb: Fix issue with VoteButton on non-loggedin state

---

src/components/Landing/HomeMenu.js
src/contexts/AppUtilsContext.js

CU-32hm4qd: Fix issue with header bg & homepage layout

---

src/components/FeedContainer/styles.js
src/components/Landing/HomeMenu.js

Fix grid layout on homepage & feed header padding

---

src/components/EditProfile/EditProfile.js
src/contexts/AuthModalContext/AuthModalContext.js

Di eth linking fix

---

src/components/RecommendedPosts/RecommendedPosts.js
src/components/UserPosts/UserPosts.js
src/pages/account/[username].js

Di recommended posts

---

src/_pages/StakingPage/Staking.js

Di staking inputhandling

---

src/components/Landing/HomeMenu.js
src/constants/data.js

CU-3katq6d: Update meta tags on homepage and feed page

---

src/utils/post_helpers.js

Di master to dev

---

src/utils/post_helpers.js

remove see more

---

src/components/GridLayout/GridLayout.js
src/contexts/AppUtilsContext.js

Di side floating

---

src/components/CustomWeb3PostEmbed/FarCasterPost.js

CU-32hm867: Fix line break issue for farcaster posts

---

src/features/RKProvider/RKProvider.js

CU-3je6tkv: Fix styling issue for rainbow kit modal

---

src/features/RKProvider/RKProvider.js

Useless commit

---

src/components/CustomTweetEmbed/Original.js
src/components/CustomTweetEmbed/Reply.js
src/pages/post/[id].js

Twitter linkpreview fix

---

src/components/CustomWeb3PostEmbed/FarCasterPost.js
src/components/CustomWeb3PostEmbed/HeaderSection.js
src/components/CustomWeb3PostEmbed/LensPost.js
src/components/PostChips/PostChips.js

external link lensPost || chip external

---

src/components/CustomTweetEmbed/Original.js
src/components/CustomTweetEmbed/Quoted.js
src/components/CustomTweetEmbed/Reply.js
src/components/CustomTweetEmbed/Retweet.js

link preview reply

---

src/components/CustomTweetEmbed/LinkPreview.js
src/components/PostCard/PostCard.js
src/components/ProfileHeader/ProfileHeader.js

use authInfo signature

---

src/pages/index.js

Add meta tags on HomePage

---

src/components/SideBar/SideBar.js
src/pages/post/[id].js

CU-3z1q62q: Close search ui on clicking post

---

src/components/Miscellaneous/CreateCollectionFab.js
src/components/ProfileHeader/ProfileHeader.js

CU-3jv524q: Fix issue with plus button overlapping on post page

---

src/pages/index.js

CU-2t9jg8e: Fix issue with header on homepage

---

src/components/PostHeader/PostHeader.js
src/components/ProfileHeader/ProfileHeader.js
src/pages/_app.js
src/pages/_document.js
src/pages/account/[username].js
src/pages/index.js
src/utils/analytics.js

CU-3yp78jk: Fix issue with Mixpanel and GA

---

src/components/ProfileHeader/FollowerSection.js
src/components/ProfileHeader/ProfileHeader.js

CU-2yfr63u: Fix styling issue with Profile Header on mobile

---

src/pages/index.js

CU-2yv1bd5: Fix issue with feed scroll on Homepage

---

src/components/VoteButton/VoteButton.js
src/contexts/AuthContext.js

Fix - slow loading time
